comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

global:
  WARNINGS_ARE_ERRORS: 1

matrix:
  - R_VERSION: devel
    GCC_PATH: mingw_32

  - R_VERSION: devel
    R_ARCH: x64
    GCC_PATH: mingw_64

  - R_VERSION: release
    R_ARCH: x64

  - R_VERSION: stable

  - R_VERSION: patched

  - R_VERSION: oldrel
    CRAN: http://cran.rstudio.com

  - R_VERSION: 3.4
    CRAN: http://cran.rstudio.com

  - R_VERSION: 3.3
    CRAN: http://cran.rstudio.com

  - R_VERSION: 3.2
    CRAN: http://cran.rstudio.com
